info:
	@echo -e 'usage: make 1s,2s,1i,2i\n1s for part 1 with sample\n1i for part 1 with input\n...'

1s:
	@gcc *1.c ../../util/util.c && ./a.out

2s:
	@gcc *2.c ../../util/util.c && ./a.out

1i:
	@gcc *1.c ../../util/util.c && ./a.out arg

2i:
	@gcc *2.c ../../util/util.c && ./a.out arg
